name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Rust target
        uses: actions/cache@v4
        with:
          path: src-tauri/target
          key: ${{ runner.os }}-rust-target-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-target-
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.12.1

      - name: Install frontend dependencies
        run: pnpm install
      - name: Build frontend
        run: pnpm build
      - name: Build Tauri app (release)
        env:
          RUSTC_WRAPPER: sccache
        run: pnpm tauri build
        working-directory: ./
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: src-tauri/target/release/aviutl2-style-config-editor.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
